spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 9206

logging:
  #file: /opt/logs/100003171/apollo-configservice.log
  file: D:/zty/demo/logs/100003171/apollo-configservice.log

  