app:
  # 如果有private的命名空间需要配置（默认application空间是private的）
  id: futian.earlyWarningMonintoring
apollo:
  # 指定apollo-configservice
  meta: http://10.190.55.65:9206
  #meta: http://10.192.19.116:9206
  bootstrap:
    enabled: true
    #对应apollo里配置的namespaces
    namespaces: application,application.yml,nearlySearchMapConfig.xml
